### ISSUE TITLE
Common's setup_logging updates basicConfig

### ISSUE THREAD

**Issue by ZlatSic** [iam-mhaseeb/sparaka#13]
Currently, the `setup_logging` function in `common` calls `basicConfig` and updates the log format, date format and the logging level. This is potentially problematic because if someone uses this library and calls this function, this will change the logging settings of the whole application using `sparaka` ([according to the documentation](https://docs.python.org/3.5/library/logging.html#logging.basicConfig), `basicConfig` is applied to the root logger), most likely overwriting user's config.

Maybe it would make sense to remove this call - these settings are going to vary from user to user anyway, it makes sense to expect from them to update the config according to their needs (i.e. date format is going to vary from location to location).

**Comment by iam-mhaseeb** [comment]
Agreed! Any other recommended way to keep loggin level this much deep?

**Comment by ZlatSic** [comment]
I think the current logging approach is good, without setting the `basicConfig` (making the `common.setup_logging` function unneccessary). It should be enough to do this in every module:

```python
import logging

LOG = logging.getLogger(__name__)
``` 

The logs are still going to be there, but it will be left to user of the library to configure them according to their needs (or use the Python defaults if they don't set anything). Feel free to assign me for this one, if you agree 🙂

**Comment by iam-mhaseeb** [comment]
Sounds good!
